kind: Deployment
apiVersion: apps/v1
metadata:
  name: poll-automation-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-app2
  template:
    metadata:
      name: pollpod2
      labels:
        app: poll-app2
    spec:
      containers:
      - name: automationcontainer1
        image: vaibhavkalel/automation1:latest
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
