kind: Deployment
apiVersion: apps/v1
metadata:
  name: poll-app-deployment0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-app0
  template:
    metadata:
      name: pollpod0
      labels:
        app: poll-app0
    spec:
      containers:
      - name: pollcontainer
        image: vaibhavkalel/pollimage1:latest
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
