kind: Deployment
apiVersion: apps/v1
metadata:
  name: poll-automation-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-app1
  template:
    metadata:
      name: pollpod1
      labels:
        app: poll-app1
    spec:
      containers:
      - name: pollcontainer2
        image: vaibhavkalel/pollimage1:latest
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
