apiVersion: v1
kind: Service
metadata:
  name: poll-automation-service
spec:
  type: NodePort
  selector:
    app: poll-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007 # You can change this to any available port number above 30000
